[project]
name = "randpal"

description = "Your friendly random pal - at your random service."
readme = "README.md"

authors = [
    { name = "Soucelover", email = "mr.ktotov@gmail.com" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Typing :: Typed",
    "Environment :: Console",
]
keywords = ["random", "cli", "generator", "dice"]

license = "MIT"
license-files = ["LICENSE"]

dynamic = ["version"]

# ===================
# Requirements (deps)
# ===================
requires-python = ">=3.14"
dependencies = []

# ============
# Build System
# ============
[project.scripts]
randpal = "randpal.__main__:main"

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"
